language: node_js
node_js:
    - "10"
    - "12"

before_script:
    - git merge test-dbs

script:
    - npm run lint
    - npm test

after_success:
#   - npm install istanbul codecov
#   - npm run coverage
#   - ./node_modules/.bin/codecov

sudo: false
